<?php
define('PLUGIN_NAME', 'my-affirmation');
define('INCLUDE_PATH', 'inc'.DIRECTORY_SEPARATOR);
define('MY_AFFIRMATION_STYLE_NAME_ONLY', PLUGIN_NAME.'-style');
define('MY_AFFIRMATION_STYLE_NAME', MY_AFFIRMATION_STYLE_NAME_ONLY.'.css');
define('MY_AFFIRMATION_SCRIPT_NAME', PLUGIN_NAME.'.js');
define('CSS_FILENAME_FROM_INC', INCLUDE_PATH.MY_AFFIRMATION_STYLE_NAME);
define('SCRIPT_FILENAME_FROM_INC', INCLUDE_PATH.MY_AFFIRMATION_SCRIPT_NAME);
define('PLUGIN_PATH', dirname(get_theme_file_path(), 2). DIRECTORY_SEPARATOR.'plugins'.DIRECTORY_SEPARATOR.PLUGIN_NAME.DIRECTORY_SEPARATOR);
define('CSS_FILENAME_FULL_PATH', PLUGIN_PATH.INCLUDE_PATH.MY_AFFIRMATION_STYLE_NAME);
define('CSS_FILENAME_URI', plugins_url(MY_AFFIRMATION_STYLE_NAME, __FILE__));